--create type category_role_type as enum ('ADMIN','MODERATOR');
--create type post_role_type as enum ('MANAGER','READER');

create table if not exists Minio_File (
    id int GENERATED BY DEFAULT AS IDENTITY,
    uid text,
    name text,
    type text,
    e_tag text,
    bucket text,
    path text,
    minio_url text,
    file_size int
);

create table if not exists Category (
    id int GENERATED BY DEFAULT AS IDENTITY,
    post_ids integer[],
    name text,
    description text,
    content text
);


create table if not exists Post (
    id int GENERATED BY DEFAULT AS IDENTITY,
    file_ids integer[],
    category_id int,
    name text,
    annotation text,
    content text
);

create table if not exists Category_Role(
    id int GENERATED BY DEFAULT AS IDENTITY,
    user_id int,
    category_id int,
    type category_role_type
);

create table if not exists Post_Role(
    id int GENERATED BY DEFAULT AS IDENTITY,
    user_id int,
    post_id int,
    type post_role_type
);

create table if not exists App_User (
    id int GENERATED BY DEFAULT AS IDENTITY,
    category_role_ids integer[],
    post_role_ids integer[],
    email text unique not null,
    password text not null,
    first_name text,
    middle_name text,
    last_name text,
    birthday date,
    placed_at date,
    phone text
);