package lab.fcpsr.suprime.models;

import lab.fcpsr.suprime.dto.EventDTO;
import lab.fcpsr.suprime.templates.Status;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

import java.time.LocalDate;

/**
 *     id int GENERATED BY DEFAULT AS IDENTITY,
 *     content text,
 *     subject text,
 *     status text,
 *     city text,
 *     location text,
 *     ekp int,
 *     start_date date,
 *     end_date date,
 *     placed_at date
 */

@Data
@NoArgsConstructor
public class Event {
    @Id
    private int id;
    private String content;
    private String subject;
    private String city;
    private String location;
    private Status status;
    private int ekp;
    private LocalDate startDate;
    private LocalDate endDate;
    private LocalDate placedAt;

    public Event(EventDTO eventDTO) {
        setContent(eventDTO.getContent());
        setSubject(eventDTO.getSubject());
        setCity(eventDTO.getCity());
        setLocation(eventDTO.getLocation());
        setStatus(eventDTO.getStatus());
        setEkp(eventDTO.getEkp());
        setStartDate(eventDTO.getStartDate());
        setEndDate(eventDTO.getEndDate());
        setPlacedAt(LocalDate.now());
    }
}
