package lab.fcpsr.suprime.models;

import lab.fcpsr.suprime.dto.EventDTO;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

import java.time.LocalDate;

/**
 *     id int GENERATED BY DEFAULT AS IDENTITY,
 *     title text,
 *     description text,
 *     event_url text,
 *     placed_at date,
 *     event_date date
 */

@Data
@NoArgsConstructor
public class Event {
    @Id
    private int id;
    private String title;
    private String description;
    private String eventUrl;
    private LocalDate placedAt;
    private LocalDate eventDate;

    public Event(EventDTO eventDTO) {
        setTitle(eventDTO.getTitle());
        setDescription(eventDTO.getDescription());
        setEventUrl(eventDTO.getEventUrl());
        setPlacedAt(LocalDate.now());
        setEventDate(eventDTO.getEventDate());
    }
}
